### ISSUE TITLE
还原储存的内容

### ISSUE THREAD

**Issue by emn178** [Xuhao/china_region_fu#19]
Hi,

重新编辑的时候, 不会还原之前储存的内容?

**Comment by Xuhao** [comment]
Hi, 如果用FormBuilder的`region_select` 方法，在编辑的时候应该可以显示之前的内容。

**Comment by emn178** [comment]
Hi,

我这样写
```Ruby
f.region_select [:province_id, :city_id, :district_id]
```
他第一个选单可以显示，但后面需要AJAX载入的部分没有显示出来，针对这部分我有Pull Request修正

**Comment by Xuhao** [comment]
@emn178 谢谢你的PR。我会尽快去看。

**Comment by Xuhao** [comment]
新版本`v0.1.0`修复了这个问题。
